[tool.poetry]
name = "composed-robot-desktop"
version = "0.1.0"
description = ""
authors = ["gregorianrants <gregorian_rants@hotmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9.2"
python-dotenv = "^1.0.1"
matplotlib = "^3.9.0"
robonet = {git = "https://github.com/gregorianrants/robonet.git"}
numpy = "1.26.4"
sympy = "^1.13.3"
opencv-contrib-python = "4.5.5.62"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
